cluster/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import InstanciaCreateView
from . import views

app_name = 'cluster'
urlpatterns = [
    path('', views.home, name='home'),    
    path('instancia/agregar', InstanciaCreateView.as_view(), name='agregar_instancia')
]

optimization/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cluster/', include('cluster.urls')),
    path('salones/', include('salones.urls')),
]

salones/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.conf.urls.static import static

app_name = 'salones'
urlpatterns = [
    path('', views.home, name='home'),  
    path('sheduling/<str:pk_salon>/', views.scheduling, name='sheduling'),
    path('sheduling/<str:pk_pro>/<int:pk_sem>/', views.scheduling_pro_sem, name='sheduling_pro_sem')  
    #path('instancia/agregar', InstanciaCreateView.as_view(), name='agregar_instancia')
]

salones/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
# Create your models here.

class Instancia(models.Model):
    id = models.AutoField(primary_key = True)
    descripcion = models.TextField('descripcion', max_length=100)
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return str(self.id)


# Dias programables
class Dia(models.Model): 
    id = models.IntegerField('id')
    abreviatura = models.CharField('abreviatura',primary_key = True,max_length=100, unique=False)
    descripcion = models.TextField('descripcion', max_length=100)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.descripcion)



# Categoria Pregrado
class CategoriaPregrado(models.Model): 
    id = models.IntegerField('id')
    abreviatura = models.CharField('abreviatura',primary_key = True,max_length=100, unique=False)
    descripcion = models.TextField('descripcion', max_length=100)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.abreviatura)


# Categoria Posgrado
class CategoriaPosgrado(models.Model): 
    id = models.IntegerField('id')
    abreviatura = models.CharField('abreviatura',primary_key = True,max_length=100, unique=False)
    descripcion = models.TextField('descripcion', max_length=100)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.abreviatura)

# Asignaturas de pregrado
class AsignaturaPregrado(models.Model): 
    id = models.IntegerField('id')
    abreviatura = models.CharField('abreviatura',primary_key = True,max_length=100, unique=False)
    descripcion = models.TextField('descripcion', max_length=100)
    numerogrupos = models.IntegerField('numerogrupos') # numero de grupos a programar de la asignatura i.
    sesionessemanales = models.IntegerField('sesionessemanales') # numero de sesiones semanales de la asignatura i.
    cuporequerido = models.IntegerField('cuporequerido') # Cupo requerido en numero de estudiantes de la asignatura i
    categoriapregrado = models.ForeignKey(CategoriaPregrado, on_delete = models.CASCADE, blank=True, null=True) # Categoria a la cual pertenece la asignatura i
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.abreviatura)


# Salones programables
class Salon(models.Model): 
    id = models.IntegerField('id')
    abreviatura = models.CharField('abreviatura',primary_key = True,max_length=100, unique=False)
    descripcion = models.TextField('descripcion', max_length=100)
    capacidad = models.IntegerField('capacidad')
    movilidad_reducida = models.IntegerField('movilidad_reducida')
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.descripcion)


# Franjas horarias
class FranjaHoraria(models.Model): 
    id = models.IntegerField('id')
    abreviatura = models.CharField('abreviatura',primary_key = True,max_length=100)
    descripcion = models.TextField('descripcion', max_length=100)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.descripcion)

# Programas de pregrado
class ProgramaPregrado(models.Model): 
    id = models.IntegerField('id')
    abreviatura = models.CharField('abreviatura',primary_key = True,max_length=100)
    descripcion = models.TextField('descripcion', max_length=100)
    semestres = models.IntegerField('semestres')  # numero de semestres del pregrado p.
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.descripcion)

# Programas de posgrado
class ProgramaPosgrado(models.Model): 
    id = models.IntegerField('id')
    abreviatura = models.CharField('abreviatura',primary_key = True,max_length=100)
    descripcion = models.TextField('descripcion', max_length=100)
    semestres = models.IntegerField('semestres')  # numero de semestres del posgrado p.
    categoriaposgrado = models.ForeignKey(CategoriaPosgrado, on_delete = models.CASCADE, blank=True, null=True) # categoria al que pertenece el posgrado p2
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.descripcion)

# Profesores
class Profesor(models.Model):
    cedula = models.IntegerField(primary_key = True)
    nombre = models.TextField('nombres', max_length=100)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.nombre)


# Profesores
class ProfesorDirectivo(models.Model):
    id = models.AutoField(primary_key = True)
    profesor = models.ForeignKey(Profesor, on_delete = models.CASCADE, blank=True, null=True)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.profesor)

# Profesores
class AsignaturaProfesor(models.Model):
    id = models.AutoField(primary_key = True)
    profesor = models.ForeignKey(Profesor, on_delete = models.CASCADE, blank=True, null=True)
    asignaturapregrado = models.ForeignKey(AsignaturaPregrado, on_delete = models.CASCADE, blank=True, null=True)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.profesor)+ "-" + str(self.asignaturapregrado)


# Franjas disponibles para la categoria pregrado o1
class FranjaPregrado(models.Model):
    id = models.AutoField(primary_key = True)
    categoriapregrado = models.ForeignKey(CategoriaPregrado, on_delete = models.CASCADE, blank=True, null=True)
    dia = models.ForeignKey(Dia, on_delete = models.CASCADE, blank=True, null=True)
    franjahoraria = models.ForeignKey(FranjaHoraria, on_delete = models.CASCADE, blank=True, null=True)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.categoriapregrado) + "-" + str(self.dia)+ "-" + str(self.franjahoraria)

# Franjas disponibles para la categoria posgrado o2
class FranjaPosgrado(models.Model):
    id = models.AutoField(primary_key = True)
    categoriaposgrado = models.ForeignKey(CategoriaPosgrado, on_delete = models.CASCADE, blank=True, null=True)
    dia = models.ForeignKey(Dia, on_delete = models.CASCADE, blank=True, null=True)
    franjahoraria = models.ForeignKey(FranjaHoraria, on_delete = models.CASCADE, blank=True, null=True)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.categoriaposgrado) + "-" + str(self.dia)+ "-" + str(self.franjahoraria)


# Salones de clase disponibles para la categoria pregado o1
class SalonPregrado(models.Model):
    id = models.AutoField(primary_key = True)
    categoriapregrado = models.ForeignKey(CategoriaPregrado, on_delete = models.CASCADE, blank=True, null=True)
    salon = models.ForeignKey(Salon, on_delete = models.CASCADE, blank=True, null=True)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.categoriapregrado) + "-" + str(self.salon) 


# Dias de clase disponibles para la categoria pregado o1
class DiaPregrado(models.Model):
    id = models.AutoField(primary_key = True)
    categoriapregrado = models.ForeignKey(CategoriaPregrado, on_delete = models.CASCADE, blank=True, null=True)
    dia = models.ForeignKey(Dia, on_delete = models.CASCADE, blank=True, null=True)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.categoriapregrado) + "-" + str(self.dia) 


# Salones de clase disponibles para la categoria posgrado o2
class SalonPosgrado(models.Model):
    id = models.AutoField(primary_key = True)
    categoriaposgrado = models.ForeignKey(CategoriaPosgrado, on_delete = models.CASCADE, blank=True, null=True)
    salon = models.ForeignKey(Salon, on_delete = models.CASCADE, blank=True, null=True)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.categoriaposgrado) + "-" + str(self.salon)




# Dias de clase disponibles para la categoria posgrado o2
class DiaPosgrado(models.Model):
    id = models.AutoField(primary_key = True)
    categoriaposgrado = models.ForeignKey(CategoriaPosgrado, on_delete = models.CASCADE, blank=True, null=True)
    dia = models.ForeignKey(Dia, on_delete = models.CASCADE, blank=True, null=True)
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.categoriaposgrado) + "-" + str(self.dia)



class W(models.Model):
    id = models.AutoField(primary_key = True)
    dia = models.ForeignKey(Dia, on_delete = models.CASCADE, blank=True, null=True,related_name='dia')
    dia1 = models.ForeignKey(Dia, on_delete = models.CASCADE, blank=True, null=True, related_name='dia1')
    instancia = models.ForeignKey(Instancia, on_delete = models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.dia) + "-" + str(self.dia1)


# asignatura de semestres del pregrado p.
class PregradoSemestreAsignatura(models.Model):
    id = models.AutoField(primary_key = True)
    programapregado = models.ForeignKey(ProgramaPregrado, on_delete = models.CASCADE, blank=True, null=True)
    semestre = models.IntegerField('semestre') 

salones/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .utils import optimizar
from .models import Salon, Resultados,Dia,FranjaHoraria,ProgramaPregrado, PregradoSemestreAsignatura, AsignaturaPregrado
# Create your views here.


def home(request):
    #instance.pprint()
    #instance.Y.display()
    #optimizar(1)
    contexto={}
    salones = Salon.objects.filter()
    programas = ProgramaPregrado.objects.filter()
    contexto['programas'] = programas
    contexto['salones']=salones

    return render(request, 'salones/index.html', contexto)


def scheduling(request, pk_salon):
    contexto={}
    franjas = FranjaHoraria.objects.filter()
    dias = Dia.objects.filter()
    existe = {}
    programacion = {}
    asignaturas = {}
    grupos = {}
    sesiones = {}
    for dia in dias:
        for franja in franjas:
            if(Resultados.objects.filter(dia=dia,franjahoraria=franja,salon=pk_salon).exists()):
                salon_dia_franja = Resultados.objects.get(dia=dia,franjahoraria=franja,salon=pk_salon)
                #programacion[str(dia.abreviatura)+"-"+str(franja.abreviatura)]=salon_dia_franja
                asignaturas[str(dia.abreviatura)+"-"+str(franja.abreviatura)]=salon_dia_franja.asignaturapregrado
                grupos[str(dia.abreviatura)+"-"+str(franja.abreviatura)]=salon_dia_franja.grupo
                sesiones[str(dia.abreviatura)+"-"+str(franja.abreviatura)]=salon_dia_franja.sesiones
                existe[str(dia.abreviatura)+"-"+str(franja.abreviatura)]=1


    contexto['franjas'] = franjas
    contexto['dias'] = dias
    contexto['asignaturas'] = asignaturas
    contexto['grupos'] =  grupos
    contexto['sesiones'] = sesiones
    contexto['existe'] = existe
    contexto['pk_salon'] = pk_salon
    print('atras bueno',programacion)
    
    return render(request, 'salones/sheduling.html', contexto)


def scheduling_pro_sem(request, pk_pro, pk_sem):
    contexto={}
    pro_pre_asig = PregradoSemestreAsignatura.objects.filter(programapregado=pk_pro,semestre=pk_sem)
    print(pro_pre_asig )
    franjas = FranjaHoraria.objects.filter()
    dias = Dia.objects.filter()
    existe = {}
    programacion = {}
    asignaturas = {}
    grupos = {}
    salones = {}
    sesiones = {}
    max_gru = [0]
    for asigna in pro_pre_asig:
        for dia in dias:
            for franja in franjas:
                grupo_asignatura =AsignaturaPregrado.objects.get(pk=asigna.asignaturapregrado)
                max_gru.append(grupo_asignatura.numerogrupos)
                for grupo in range(1,grupo_asignatura.numerogrupos+1):
                    if(Resultados.objects.filter(dia=dia,franjahoraria=franja,asignaturapregrado=asigna.asignaturapregrado,grupo=grupo).exists()):
                        print(Resultados.objects.filter(dia=dia,franjahoraria=franja,asignaturapregrado=asigna.asignaturapregrado))
                        salon_dia_franja = Resultados.objects.get(dia=dia,franjahoraria=franja,asignaturapregrado=asigna.asignaturapregrado,grupo=grupo)
                        asignaturas[str(salon_dia_franja.grupo)+"-"+str(dia.abreviatura)+"-"+str(franja.abreviatura)]=salon_dia_franja.asignaturapregrado
                        grupos[str(salon_dia_franja.grupo)+"-"+str(dia.abreviatura)+"-"+str(franja.abreviatura)]=salon_dia_franja.grupo
                        sesiones[str(salon_dia_franja.grupo)+"-"+str(dia.abreviatura)+"-"+str(franja.abreviatura)]=salon_dia_franja.sesiones
                        salones[str(salon_dia_franja.grupo)+"-"+str(dia.abreviatura)+"-"+str(franja.abreviatura)]=salon_dia_franja.salon
                        existe[str(salon_dia_franja.grupo)+"-"+str(dia.abreviatura)+"-"+str(franja.abreviatura)]=1
                
    num_grupos = max(max_gru)
    #print('milton----------------------------',max(max_gru))
    contexto['franjas'] = franjas
    contexto['dias'] = dias
    contexto['asignaturas'] = asignaturas
    contexto['grupos'] =  grupos
    contexto['sesiones'] = sesiones
    contexto['existe'] = existe
    contexto['salones'] = salones
    contexto['num_grupos'] = num_grupos
    contexto['programa'] = pk_pro
    contexto['semestre'] = pk_sem
    #contexto['cont'] = cont
    print('atras bueno',existe)
    
    return render(request, 'salones/sheduling_pre_sem.html', contexto)

salones/templates/salones/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Programacion de salones{% endblock %}</title>
    {% load static %}
    {% load template_filters %}
    <link rel="stylesheet" href="{% static 'salones/css/style.css' %}">
</head>
<style>

</style>

<body>
    <h4>Hola Milton A</h4>
    <div>
        {% for salon in salones %}
        <a href="{% url 'salones:sheduling' pk_salon=salon.abreviatura %}" class="btn btn-primary btn-block mb-2">Ver el
            salon : {{salon.abreviatura}}</a>
        <br>
        {% endfor %}
    </div>


    <div>
        {% for programa in programas %}
        <p>Ver la programación del programa : {{programa.abreviatura}}</p>
        {% for i in programa.semestres|semestres %}
        
        <a href="{% url 'salones:sheduling_pro_sem' pk_pro=programa.abreviatura pk_sem=i %}" class="btn btn-primary btn-block mb-2">Del semestre : {{i}}</a>
        
        {% endfor %}
        {% endfor %}
    </div>
    <!-- <div class='tab'>
        <table border='0' cellpadding='0' cellspacing='0'>
            <tr class='days'>
                <th></th>
                <th>Monday</th>
                <th>Tuesday</th>
                <th>Wednesday</th>
                <th>Thursday</th>
                <th>Friday</th>
            </tr>
            <tr>
                <td class='time'>9.00</td>
                <td class='cs335 blue' data-tooltip='Software Engineering &amp; Software Process'>CS335 [JH1]</td>
                <td class='cs426 purple' data-tooltip='Computer Graphics'>CS426 [CS1]</td>
                <td></td>
                <td></td>
                <td>-</td>
            </tr>
            <tr>
                <td class='time'>10.00</td>
                <td></td>
                <td class='cs335 blue lab' data-tooltip='Software Engineering &amp; Software Process'>CS335 [Lab]</td>
                <td class='md352 green' data-tooltip='Multimedia Production &amp; Management'>MD352 [Kairos]</td>
                <td></td>
                <td>-</td>
            </tr>
            <tr>
                <td class='time'>11.00</td>
                <td></td>
                <td class='cs335 blue lab' data-tooltip='Software Engineering &amp; Software Process'>CS335 [Lab]</td>
                <td class='md352 green' data-tooltip='Multimedia Production &amp; Management'>MD352 [Kairos]</td>
                <td class='cs240 orange' data-tooltip='Operating Systems'>CS240 [CH]</td>
                <td>-</td>
            </tr>
            <tr>
                <td class='time'>12.00</td>
                <td></td>
                <td class='md303 navy' data-tooltip='Media &amp; Globalisation'>MD303 [CS2]</td>
                <td class='md313 red' data-tooltip='Special Topic: Multiculturalism &amp; Nationalism'>MD313 [Iontas]
                </td>
                <td></td>
                <td>-</td>
            </tr>
            <tr>
                <td class='time'>13.00</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>-</td>
            </tr>
            <tr>
                <td class='time'>14.00</td>
                <td></td>
                <td></td>
                <td class='cs426 purple' data-tooltip='Computer Graphics'>CS426 [CS2]</td>
                <td class='cs240 orange' data-tooltip='Operating Systems'>CS240 [TH1]</td>
                <td>-</td>
            </tr>
            <tr>
                <td class='time'>15.00</td>
                <td></td>
                <td></td>
                <td></td>
                <td class='cs240 orange lab' data-tooltip='Operating Systems'>CS240 [Lab]</td>
                <td>-</td>
            </tr>
            <tr>
                <td class='time'>16.00</td>
                <td></td>
                <td></td>
                <td></td>
                <td class='cs240 orange lab' data-tooltip='Operating Systems'>CS240 [Lab]</td>
                <td>-</td>
            </tr>
            <tr>
                <td class='time'>17.00</td>
                <td class='cs335 blue' data-tooltip='Software Engineering &amp; Software Process'>CS335 [TH1]</td>
                <td></td>
                <td></td>
                <td></td>
                <td>-</td>
            </tr>
        </table>
    </div> -->

</body>

</html>

salones/templates/salones/sheduling.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Programacion de salones{% endblock %}</title>
    {% load static %}
    {% load template_filters %}
    <link rel="stylesheet" href="{% static 'salones/css/style.css' %}">
</head>
<style>

</style>

<body>
    <h4>Programación salon : {{pk_salon}}</h4>
    <br>
    <div class='tab'>
        <table border='0' cellpadding='0' cellspacing='0'>
            <tr class='days'>
                <th></th>
                {% for dia in dias %}
                <th>{{dia.descripcion}}</th>
                {% endfor %}

            </tr>

            {% for franja in franjas %}
            <tr>
                <td class='time'>{{franja.descripcion}}</td>
                {% for dia in dias %}
                {% with dia_id=dia.abreviatura %}
                {% with check2=dia_id|add:'-' %}
                {% with check=check2|add:franja.abreviatura %}
                {% if  existe|get_item:check == 1 %}

                {% if  dia.abreviatura == 'Lun' %}
                <td class='md352 green' data-tooltip='{{ asignaturas|get_item:check}}'>
                    {{ asignaturas|get_item:check}}-{{ grupos|get_item:check}}-{{ sesiones|get_item:check}}</td>
                {% endif %}

                {% if  dia.abreviatura == 'Mar' %}
                <td class='cs335 blue' data-tooltip='{{ asignaturas|get_item:check}}'>
                    {{ asignaturas|get_item:check}}-{{ grupos|get_item:check}}-{{ sesiones|get_item:check}}</td>
                {% endif %}

                {% if  dia.abreviatura == 'Mie' %}
                <td class='cs426 purple' data-tooltip='{{ asignaturas|get_item:check}}'>
                    {{ asignaturas|get_item:check}}-{{ grupos|get_item:check}}-{{ sesiones|get_item:check}}</td>
                {% endif %}

                {% if  dia.abreviatura == 'Jue' %}
                <td class='cs240 orange' data-tooltip='{{ asignaturas|get_item:check}}'>
                    {{ asignaturas|get_item:check}}-{{ grupos|get_item:check}}-{{ sesiones|get_item:check}}</td>
                {% endif %}

                {% if  dia.abreviatura == 'Vie' %}
                <td class='md313 red' data-tooltip='{{ asignaturas|get_item:check}}'>
                    {{ asignaturas|get_item:check}}-{{ grupos|get_item:check}}-{{ sesiones|get_item:check}}</td>
                {% endif %}

                {% if  dia.abreviatura == 'Sab' %}
                <td class='md303 navy' data-tooltip='{{ asignaturas|get_item:check}}'>
                    {{ asignaturas|get_item:check}}-{{ grupos|get_item:check}}-{{ sesiones|get_item:check}}</td>
                {% endif %}
                {% else %}
                <td></td>
                {% endif %}
                {% endwith %}
                {% endwith %}
                {% endwith %}
                {% endfor %}

            </tr>
            {% endfor %}
        </table>
    </div>

</body>

</html>

salones/templates/salones/sheduling_pre_sem.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Programacion de salones{% endblock %}</title>
    {% load static %}
    {% load template_filters %}
    <link rel="stylesheet" href="{% static 'salones/css/style.css' %}">
</head>
<style>

</style>

<body>
    <h4>Programación del programa: {{programa}} y del semestre: {{semestre}}</h4>
    <br>
    <div class='tab'>
        {% for gr in num_grupos|semestres %}
        <table border='0' cellpadding='0' cellspacing='0'>
            <tr class='days'>
                <th>Grupo: {{gr}}</th>
                {% for dia in dias %}
                <th>{{dia.descripcion}}</th>
                {% endfor %}

            </tr>
            {% for franja in franjas %}
            <tr>
                <td class='time'>{{franja.descripcion}}</td>
                {% for dia in dias %}
                {% with grupo_id=gr|stringformat:"i" %}
                {% with check=grupo_id|add:'-' %}
                {% with check0=check|add:dia.abreviatura %}
                {% with check1=check0|add:'-' %}
                {% with check2=check1|add:franja.abreviatura %}
                {% if  existe|get_item:check2 == 1 %}
                {% if  dia.abreviatura == 'Lun' %}
                <td class='md352 green' data-tooltip='Salon: {{ salones|get_item:check2}}'>
                    {{ asignaturas|get_item:check2}}-{{ grupos|get_item:check2}}-{{ sesiones|get_item:check2}}</td>
                {% endif %}

                {% if  dia.abreviatura == 'Mar' %}
                <td class='cs335 blue' data-tooltip='Salon: {{ salones|get_item:check2}}'>
                    {{ asignaturas|get_item:check2}}-{{ grupos|get_item:check2}}-{{ sesiones|get_item:check2}}</td>
                {% endif %}

                {% if  dia.abreviatura == 'Mie' %}
                <td class='cs426 purple' data-tooltip='Salon: {{ salones|get_item:check2}}'>
                    {{ asignaturas|get_item:check2}}-{{ grupos|get_item:check2}}-{{ sesiones|get_item:check2}}</td>
                {% endif %}

                {% if  dia.abreviatura == 'Jue' %}
                <td class='cs240 orange' data-tooltip='Salon: {{ salones|get_item:check2}}'>
                    {{ asignaturas|get_item:check2}}-{{ grupos|get_item:check2}}-{{ sesiones|get_item:check2}}</td>
                {% endif %}

                {% if  dia.abreviatura == 'Vie' %}
                <td class='md313 red' data-tooltip='Salon: {{ salones|get_item:check2}}'>
                    {{ asignaturas|get_item:check2}}-{{ grupos|get_item:check2}}-{{ sesiones|get_item:check2}}</td>
                {% endif %}

                {% if  dia.abreviatura == 'Sab' %}
                <td class='md303 navy' data-tooltip='Salon: {{ salones|get_item:check2}}'>
                    {{ asignaturas|get_item:check2}}-{{ grupos|get_item:check2}}-{{ sesiones|get_item:check2}}</td>
                {% endif %}
                {% else %}
                <td></td>
                {% endif %}
                {% endwith %}
                {% endwith %}
                {% endwith %}
                {% endwith %}
                {% endwith %}
                {% endfor %}
            </tr>
            {% endfor %}
            {% endfor %}


        </table>
    </div>

</body>

</html>